from pydantic import BaseModel, Field


class FitAgentInput(BaseModel):
    """
    Input schema for FitAgent analysis.
    This represents the data sent from the frontend to the backend.
    """

    skills: str = Field(
        ...,
        description="Student's skills written as free text"
    )

    interests: str = Field(
        ...,
        description="Student's interests written as free text"
    )

    job_description: str = Field(
        ...,
        description="Internship job description text"
    )


class FitAgentOutput(BaseModel):
    """
    Output schema for FitAgent analysis.
    This represents the structured AI-generated response.
    """

    match_summary: str = Field(
        ...,
        description="Summary explaining how well the student matches the internship"
    )

    skill_gaps: str = Field(
        ...,
        description="Explanation of missing or weak skills compared to the job description"
    )

    recommendation: str = Field(
        ...,
        description="Actionable recommendation for the student"
    )

    resume_text: str = Field(
        ...,
        description="JD-aligned resume content generated by the AI"
    )

    confidence_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="ATS-style confidence score between 0 and 100"
    )
