from pydantic import BaseModel, Field


class FitAgentInput(BaseModel):
    """
    Input schema for FitAgent analysis.
    This represents the data sent from the frontend to the backend.
    """

    skills: str = Field(
        ...,
        description="Student's skills written as free text"
    )

    interests: str = Field(
        ...,
        description="Student's interests written as free text"
    )

    job_description: str = Field(
        ...,
        description="Internship job description text"
    )


class FitAgentOutput(BaseModel):
    """
    Output schema for FitAgent analysis.
    This represents the structured AI-generated response.
    """

    match_summary: str = Field(
        ...,
        description="Summary explaining how well the student matches the internship"
    )

    skill_gaps: str = Field(
        ...,
        description="Explanation of missing or weak skills compared to the job description"
    )

    recommendation: str = Field(
        ...,
        description="Actionable recommendation for the student"
    )

    resume_text: str = Field(
        ...,
        description="JD-aligned resume content generated by the AI"
    )

    confidence_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="ATS-style confidence score between 0 and 100"
    )

from typing import List, Dict


class BeforeAfterExample(BaseModel):
    before: str = Field(
        ...,
        description="Original resume line before improvement"
    )
    after: str = Field(
        ...,
        description="Improved version of the resume line"
    )


class SectionAnalysis(BaseModel):
    issues: List[str] = Field(
        default_factory=list,
        description="Identified issues in this resume section"
    )
    why_it_matters: str = Field(
        ...,
        description="Explanation of why these issues reduce ATS confidence"
    )
    suggestions: List[str] = Field(
        default_factory=list,
        description="Actionable improvement suggestions for this section"
    )
    before_after_examples: List[BeforeAfterExample] = Field(
        default_factory=list,
        description="Exact before and after rewrite examples"
    )


class ResumeConfidenceOutput(BaseModel):
    current_confidence_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="ATS-style confidence score before improvements"
    )

    confidence_summary: str = Field(
        ...,
        description="High-level explanation of the confidence score"
    )

    section_analysis: Dict[str, SectionAnalysis] = Field(
        ...,
        description="Section-wise resume analysis mapped by section name"
    )

    improved_resume_text: str = Field(
        ...,
        description="Fully improved resume content (text only, no formatting)"
    )

    improved_confidence_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="ATS-style confidence score after improvements"
    )

